### POST /api/museums/ crea un museo 
POST http://localhost:3000/api/museums
Content-Type: application/json

{
    "name": "Museo de Arte Contemporáneo",
    "city" : "Sevilla",
    "annual_budget" : 500000.00,
    "is_public" : true,
    "opening_date" : "2010-05-20"
}

### GET /api/museums/:id recupera un museo
GET http://localhost:3000/api/museums/1
### GET /api/museums/:id recupera un museo - NOT FOUND(404)
GET http://localhost:3000/api/museums/50

### PUT /api/museums/:id actualiza un museo
PUT http://localhost:3000/api/museums/19
Content-Type: application/json

{
    "name": "Museo de Arte Moderno",
    "city" : "Barcelona",
    "annual_budget" : 750000.00,
    "is_public" : false,
    "opening_date" : "2015-09-15"
}

### PUT /api/museums/:id actualiza un museo - NOT FOUND(404)
PUT http://localhost:3000/api/museums/50
Content-Type: application/json

{
    "name": "Museo de Arte Moderno",
    "city" : "Barcelona",
    "annual_budget" : 750000.00,
    "is_public" : false,
    "opening_date" : "2015-09-15"
}

### DELETE /api/museums/:id elimina un museo
DELETE http://localhost:3000/api/museums/1

### DELETE /api/museums/:id elimina un museo - NOT FOUND(404)
DELETE http://localhost:3000/api/museums/50

### GET /api/museums recupera todos los museos
GET http://localhost:3000/api/museums