### POST /api/museums/ crea un museo
POST http://localhost:3000/api/museums
Content-Type: application/json

{
    "name": "Museo de Arte Contemporáneo",
    "city" : "Sevilla",
    "annual_budget" : 500000.00,
    "is_public" : true,
    "opening_date" : "2010-05-20"
}

### GET /api/museums/:id recupera un museo
GET http://localhost:3000/api/museums/1
### GET /api/museums/:id recupera un museo - NOT FOUND(404)
GET http://localhost:3000/api/museums/50

### PUT /api/museums/:id actualiza un museo
PUT http://localhost:3000/api/museums/21
Content-Type: application/json

{
    "name": "Museo de Arte Moderno",
    "city" : "Barcelona",
    "annual_budget" : 750000.00,
    "is_public" : false,
    "opening_date" : "2015-09-15"
}

### PUT /api/museums/:id actualiza un museo - NOT FOUND(404)
PUT http://localhost:3000/api/museums/50
Content-Type: application/json

{
    "name": "Museo de Arte Moderno",
    "city" : "Barcelona",
    "annual_budget" : 750000.00,
    "is_public" : false,
    "opening_date" : "2015-09-15"
}

### DELETE /api/museums/:id elimina un museo
DELETE http://localhost:3000/api/museums/21

### DELETE /api/museums/:id elimina un museo - NOT FOUND(404)
DELETE http://localhost:3000/api/museums/50

### GET /api/museums recupera todos los museos
GET http://localhost:3000/api/museums

### GET /api/museums/budget recupera museos por rango de presupuesto
GET http://localhost:3000/api/museums/budget?min=100&max=300000

### GET /api/museums/budget sin parámetros
GET http://localhost:3000/api/museums/budget

### GET /api/museums/budget parametros incorrectos
GET http://localhost:3000/api/museums/budget?min=300&max=200


// NECESARIO PARA LA PRACTICA DE REACT
### GET /api/museums/between recupera museos entre fechas
GET http://localhost:3000/api/museums/between?from=2015-01-01&to=2026-01-01

### GET /api/museums/between sin fechas
GET http://localhost:3000/api/museums/between

### GET /api/museums/between fechas incorrectas
GET http://localhost:3000/api/museums/between?from=2022-01-01&to=2010-01-01