### POST /api/rooms crea una sala
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
    "name": "Sala de Arte Contemporáneo",
    "capacity": 120,
    "area": 350.50,
    "is_climatized": true,
    "opening_date": "2015-03-10",
    "museum_id": 2
}

### GET /api/rooms/:id recupera un sala
GET http://localhost:3000/api/rooms/1
### GET /api/rooms/:id recupera un sala - NOT FOUND(404)
GET http://localhost:3000/api/rooms/50

### PUT /api/rooms/:id actualiza una sala
PUT http://localhost:3000/api/rooms/2
Content-Type: application/json

{
    "name": "Sala de Escultura",
    "capacity": 80,
    "area": 200.00,
    "is_climatized": false,
    "opening_date": "2018-07-22",
    "museum_id": 2
}

### PUT /api/rooms/:id actualiza una sala - NOT FOUND(404)
PUT http://localhost:3000/api/rooms/50
Content-Type: application/json

{
    "name": "Sala de Escultura",
    "capacity": 80,
    "area": 200.00,
    "is_climatized": false,
    "opening_date": "2018-07-22",
    "museum_id": 1
}

### DELETE /api/rooms/:id elimina una sala
DELETE http://localhost:3000/api/rooms/1
### DELETE /api/rooms/:id elimina una sala - NOT FOUND(404)
DELETE http://localhost:3000/api/rooms/50

### GET /api/rooms recupera todos los salas
GET http://localhost:3000/api/rooms

### GET /api/rooms/ recupera salas por rango de área
GET http://localhost:3000/api/rooms/area?min=200&max=500

### GET /api/rooms/area sin parámetros
GET http://localhost:3000/api/rooms/area    

### GET /api/rooms/area parametros incorrectos
GET http://localhost:3000/api/rooms/area?min=300&max=200


